[add]:Import, export button for teachers and syllabus creation is improoved
werbhq/attendo-admin pull request #36
Opened 2023-04-21 17:20 UTC by seramg

close #30 
close #35 

@mak626  look into the syllabus creation. semester value by default while creation is 0

2023-04-21 17:51 UTC, mak626 requested changes
In additon to my changes. In the code give space between functions. **Code readability is hard** with no spaces b/w different functions

2023-04-21 17:51 UTC, mak626 commented on src/Utils/helpers.ts
> +    } else if (value && Array.isArray(value)) {
remove the tree of if else if... 
use if return paradigm.

2023-04-21 17:51 UTC, mak626 commented on src/pages/authTeachers/Create.tsx
> +            console.log(e.data.includes(data));
remove console log

2023-04-21 17:51 UTC, mak626 commented on src/pages/authTeachers/Show.tsx
> +    const record = useShowController().record as AuthorizedTeacher;
use destructuring

2023-04-21 17:51 UTC, mak626 commented on src/pages/authTeachers/Show.tsx
> +            {loading ? (
instead of ternary try to give something like

if(loading) return <>Loading..</>

return <>Other component</>

2023-04-21 17:51 UTC, mak626 commented on src/pages/authTeachers/components/Button.tsx
> +                    refresh();
move the refresh out of the if else

2023-04-21 17:51 UTC, mak626 commented on src/pages/subjects/List.tsx
> +            {/* <EditButton /> */}
Is this intentional or mistake?

2023-04-21 17:51 UTC, mak626 commented on src/provider/custom/classroom.ts
> +        console.log('Updating classroom doc');
remove log

2023-04-21 17:51 UTC, mak626 commented on src/pages/subjects/index.tsx
> +    // edit: SubjectEdit,
is this intentional? The subject edit page still seems to exist

2023-04-21 17:51 UTC, mak626 commented on src/pages/subjects/components/show/SubjectTable.tsx
> +        const semesterIndex = data.semesters.findIndex((e) => e.semester === record.semester); //0
whats the 
//0 //0 //8 comments
supposed to mean?

2023-04-21 17:51 UTC, mak626 commented on src/pages/subjects/components/show/SubjectTable.tsx
> +                                        style={{
is there no way to avoid giving this custom styling.
Also please use mui theme variables. dont hardcode the colors. use primary secondary

2023-04-21 17:51 UTC, mak626 commented on src/pages/subjects/components/show/SubjectTable.tsx
> +                                            color: '#2196f3',
is there no way to avoid giving this custom styling.
Also please use mui theme variables. dont hardcode the colors. use primary secondary

2023-04-21 17:52 UTC, mak626 commented
Also fix the following odd color border in subject screen
![image](https://user-images.githubusercontent.com/60577077/233702687-57e36285-d2c8-4da1-9029-62932d32fcfc.png)

2023-04-23 19:54 UTC, mak626 requested changes

2023-04-23 19:54 UTC, mak626 commented on src/pages/authTeachers/Show.tsx
> +            return
Please use return ( <> </>)
Install eslint if u havent.

2023-04-23 19:54 UTC, mak626 commented on src/Utils/helpers.ts
> +    if (value && regex.test(value)) return 'Value must not contain a number';
move this to top. and bring that forloop one down. and also wrap the for loop one with { } brackets

2023-04-24 18:39 UTC, seramg commented on src/pages/authTeachers/Show.tsx
> +            return
Used ternary instead @mak626

2023-04-24 18:39 UTC, seramg commented on src/Utils/helpers.ts
> +    if (value && regex.test(value)) return 'Value must not contain a number';
Moved

2023-04-27 20:23 UTC, mak626 approved these changes

2023-04-27 20:23 UTC, merged